image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - export TAG=$(docker run --rm "$CI_REGISTRY_IMAGE:latest" cat /manifest.txt | awk NR==2)
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker tag "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE:$TAG"
    - docker push "$CI_REGISTRY_IMAGE:$TAG"
    - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
    - docker tag "$CI_REGISTRY_IMAGE:latest" "$DOCKER_USERNAME/$CI_PROJECT_NAME:latest"
    - docker push "$DOCKER_USERNAME/$CI_PROJECT_NAME:latest"
    - docker tag "$DOCKER_USERNAME/$CI_PROJECT_NAME:latest" "$DOCKER_USERNAME/$CI_PROJECT_NAME:$TAG"
    - docker push "$DOCKER_USERNAME/$CI_PROJECT_NAME:$TAG"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - no-push
    - master

build-no-push:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - export TAG=$(docker run --rm "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" cat /manifest.txt | awk NR==2)
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE:$TAG"
  only:
    - no-push
